'use client';

import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';
import { Payment } from '@/lib/types';

const styles = StyleSheet.create({
    page: {
        fontFamily: 'Helvetica',
        fontSize: 10,
        padding: 30,
        backgroundColor: '#FFFFFF',
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#e2e8f0',
        paddingBottom: 10,
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#1a202c',
        marginBottom: 5,
    },
    subtitle: {
        fontSize: 12,
        color: '#718096',
    },
    reportDetails: {
        fontSize: 10,
        color: '#4a5568',
        marginTop: 5,
    },
    table: {
        display: 'flex',
        width: 'auto',
        borderStyle: 'solid',
        borderWidth: 1,
        borderColor: '#e2e8f0',
        marginTop: 10,
    },
    tableRow: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#e2e8f0',
        minHeight: 25,
        alignItems: 'center',
    },
    tableHeader: {
        backgroundColor: '#f7fafc',
        fontWeight: 'bold',
    },
    colDate: { width: '15%', padding: 5 },
    colTenant: { width: '25%', padding: 5 },
    colProperty: { width: '25%', padding: 5 },
    colType: { width: '15%', padding: 5 },
    colAmount: { width: '20%', padding: 5, textAlign: 'right' },

    totalRow: {
        flexDirection: 'row',
        marginTop: 10,
        justifyContent: 'flex-end',
        paddingRight: 5,
    },
    totalText: {
        fontSize: 12,
        fontWeight: 'bold',
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 30,
        right: 30,
        textAlign: 'center',
        fontSize: 8,
        color: '#a0aec0',
    }
});

const formatCurrency = (amount: number) => {
    return amount.toFixed(0).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
};

// Helper to format timestamp or date object
const formatDate = (date: any) => {
    if (!date) return '';
    const d = date.toDate ? date.toDate() : new Date(date);
    return d.toLocaleDateString();
};

const FinancialReportDocument = ({ payments, month, year }: { payments: Payment[], month: string, year: string }) => {
    const totalRevenue = payments.reduce((sum, p) => sum + (Number(p.amount) || 0), 0);

    return (
        <Document>
            <Page size="A4" style={styles.page}>
                <View style={styles.header}>
                    <Text style={styles.title}>Monthly Financial Report</Text>
                    <Text style={styles.subtitle}>Senra Technologies Property Management</Text>
                    <Text style={styles.reportDetails}>Period: {month} {year}</Text>
                    <Text style={styles.reportDetails}>Generated: {new Date().toLocaleDateString()}</Text>
                </View>

                <View style={styles.table}>
                    <View style={[styles.tableRow, styles.tableHeader]}>
                        <Text style={styles.colDate}>Date</Text>
                        <Text style={styles.colTenant}>Tenant</Text>
                        <Text style={styles.colProperty}>Property</Text>
                        <Text style={styles.colType}>Type</Text>
                        <Text style={styles.colAmount}>Amount (UGX)</Text>
                    </View>

                    {payments.length === 0 ? (
                        <View style={styles.tableRow}>
                            <Text style={{ padding: 10, textAlign: 'center', width: '100%' }}>No payments found for this period.</Text>
                        </View>
                    ) : (
                        payments.map((p) => (
                            <View key={p.id} style={styles.tableRow}>
                                <Text style={styles.colDate}>{formatDate(p.date)}</Text>
                                <Text style={styles.colTenant}>{p.tenantName || 'N/A'}</Text>
                                <Text style={styles.colProperty}>{p.propertyName || 'N/A'}</Text>
                                <Text style={styles.colType}>{p.type}</Text>
                                <Text style={styles.colAmount}>{formatCurrency(p.amount)}</Text>
                            </View>
                        ))
                    )}
                </View>

                <View style={styles.totalRow}>
                    <Text style={styles.totalText}>Total Collected: UGX {formatCurrency(totalRevenue)}</Text>
                </View>

                <View style={styles.footer}>
                    <Text>Confidential Financial Document - Generated by Senra</Text>
                </View>
            </Page>
        </Document>
    );
};

export default FinancialReportDocument;
