import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 11,
    padding: 30,
    flexDirection: 'column',
    backgroundColor: '#FFFFFF'
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 2,
    borderBottomColor: '#1a202c',
    paddingBottom: 5,
  },
  headerLeft: {
    flexDirection: 'column',
  },
  headerRight: {
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1a202c',
  },
  subtitle: {
    fontSize: 10,
    color: '#718096',
  },
  receiptInfo: {
    fontSize: 12,
    color: '#718096',
  },
  section: {
    margin: 10,
    padding: 10,
  },
  billedTo: {
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  billedToText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#1a202c',
  },
  billedToInfo: {
    fontSize: 10,
    color: '#718096',
  },
  table: {
    display: 'flex',
    width: 'auto',
    marginTop: 20,
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomColor: '#e2e8f0',
    borderBottomWidth: 1,
    alignItems: 'center',
    height: 24,
  },
  tableHeader: {
    backgroundColor: '#f7fafc',
  },
  tableColHeader: {
    width: '70%',
    padding: 5,
    fontWeight: 'bold',
  },
  tableCol: {
    width: '70%',
    padding: 5,
  },
  tableColAmountHeader: {
    width: '30%',
    padding: 5,
    fontWeight: 'bold',
    textAlign: 'right',
  },
  tableColAmount: {
    width: '30%',
    padding: 5,
    textAlign: 'right',
  },
  summary: {
    marginTop: 20,
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '50%',
    paddingTop: 5,
    paddingBottom: 5,
  },
  summaryLabel: {
    fontWeight: 'bold',
  },
  total: {
    borderTopWidth: 2,
    borderTopColor: '#1a202c',
    marginTop: 5,
    paddingTop: 5,
  },
  totalLabel: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 10,
    color: '#718096',
  }
});

const ReceiptDocument = ({ payment }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <View style={styles.headerLeft}>
          <Text style={styles.title}>Karibu Properties</Text>
          <Text style={styles.subtitle}>Simplified Property Management</Text>
        </View>
        <View style={styles.headerRight}>
          <Text style={styles.receiptInfo}>Receipt #{payment.receiptNumber}</Text>
        </View>
      </View>

      <View style={styles.billedTo}>
        <View>
          <Text style={styles.billedToText}>Billed To</Text>
          <Text>{payment.tenantName}</Text>
          <Text style={styles.billedToInfo}>{payment.propertyName} - {payment.unitName}</Text>
        </View>
        <View style={{alignItems: 'flex-end'}}>
          <Text style={styles.billedToText}>Payment Date</Text>
          <Text>{payment.date}</Text>
        </View>
      </View>

      <View style={styles.table}>
        <View style={[styles.tableRow, styles.tableHeader]}>
          <Text style={styles.tableColHeader}>Description</Text>
          <Text style={styles.tableColAmountHeader}>Amount</Text>
        </View>
        <View style={styles.tableRow}>
          <Text style={styles.tableCol}>Rent Payment for {payment.unitName}</Text>
          <Text style={styles.tableColAmount}>${payment.amount.toLocaleString()}</Text>
        </View>
      </View>

      <View style={styles.summary}>
        <View style={styles.summaryRow}>
          <Text style={styles.summaryLabel}>Amount Paid</Text>
          <Text>${payment.amount.toLocaleString()}</Text>
        </View>
        <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Remaining Balance</Text>
            <Text>${(payment.balanceAfterPayment ?? 0).toLocaleString()}</Text>
        </View>
        <View style={[styles.summaryRow, styles.total]}>
          <Text style={styles.totalLabel}>Total Paid</Text>
          <Text style={styles.totalLabel}>${payment.amount.toLocaleString()}</Text>
        </View>
      </View>

      <View style={styles.footer}>
        <Text>Thank you for your payment!</Text>
        <Text>Generated by Karibu</Text>
      </View>
    </Page>
  </Document>
);

export default ReceiptDocument;
